
standard_tax_cols <- tibble::tribble(
  ~atributo, ~descricao,
  "rendimentos_tributaveis", "Somatório do total de rendimentos tributáveis (titular e dependentes).",
  "rendimentos_sujeitos_a_tributacao_exclusiva", "Somatório do total de rendimentos sujeitos à tributação exclusiva/definitiva.",
  "rendimentos_isentos", "Somatório do total de rendimentos isentos e não tributáveis.",
  "deducao_previdenciaria_total", "Somatório do total de deduções previdenciárias (Oficial, RRA, Privada e FAPI).",
  "deducoes_previdencia_oficial", "Somatório das deduções para previdência oficial e complementar pública.",
  "deducoes_prev_rra", "Deduções para previdência oficial sobre rendimentos recebidos acumuladamente.",
  "deducoes_previdencia_privada_e_fapi", "Deduções para previdência complementar privada e FAPI.",
  "deducoes_com_dependentes", "Somatório do total de deduções com dependentes.",
  "deducoes_com_instrucao", "Somatório do total de deduções com despesas de instrução.",
  "deducoes_com_despesas_medicas", "Somatório do total de deduções com despesas médicas.",
  "deducao_de_livro_caixa", "Somatório do total de deduções com Livro Caixa.",
  "deducoes_com_pensao_alimenticia_total", "Somatório das deduções com pensões alimentícias (judiciais e escriturais).",
  "deducoes_com_pensao_alimenticia_judicial", "Somatório das deduções com pensões alimentícias judiciais.",
  "deducoes_com_pensao_alimenticia_escritural", "Somatório das deduções com pensões alimentícias escriturais.",
  "deducoes_com_pensao_alimenticia_rra", "Somatório das deduções com pensões alimentícias de RRA.",
  "desconto_padrao", "Somatório do desconto padrão (para declarações simplificadas).",
  "base_de_calculo_rtl", "Somatório do total da base de cálculo do IRPF.",
  "imposto_devido", "Somatório do imposto devido apurado.",
  "deducao_de_incentivo", "Somatório das deduções de incentivo (doações permitidas).",
  "imposto_devido_1", "Diferença entre Imposto Devido e a Dedução de Incentivo.",
  "imposto_devido_rra", "Imposto devido referente aos rendimentos RRA.",
  "imposto_total", "Somatório do imposto total (Imposto Devido 1 + RRA).",
  "imposto_pago", "Imposto retido na fonte ou pago via DARF.",
  "imposto_a_pagar", "Diferença positiva entre o imposto devido e o pago.",
  "imposto_a_restituir", "Diferença negativa entre o imposto devido e o pago.",
  "dividas_e_onus", "Somatório das dívidas e ônus declarados.",
  "doacoes_e_herancas_recebidas", "Somatório das doações e heranças recebidas.",
  "bens_e_direitos", "Somatório de todos os bens e direitos declarados.",
  "previdencia_complementar_vgbl", "Valores informados a título de VGBL.",
  "valores_pagos_com_previdencia_complementar_pgbl", "Valores pagos a título de PGBL.",
  "valores_pagos_com_previdencia_complementar_de_natureza_publica", "Valores pagos a previdência complementar pública.",
  "valores_pagos_com_fapi", "Valores pagos a título de FAPI.",
  "despesas_com_instrucao", "Somatório das despesas com instrução apresentadas.",
  "despesas_medicas", "Somatório das despesas médicas apresentadas.",
  "pensao_alimenticia_judicial", "Somatório das despesas com pensão alimentícia judicial.",
  "despesas_com_pensao_alimenticia_escritural", "Somatório das despesas com pensão alimentícia escritural.",
  "despesas_com_profissionais_liberais", "Somatório das despesas realizadas com profissionais liberais.",
  "despesas_com_arrendamento_rural", "Somatório das despesas com arrendamento rural.",
  "outras_despesas", "Somatório de outras despesas realizadas.",
  "doacoes_efetuadas", "Somatório das doações efetuadas."
)

irpf_sections_catalog <- tibble::tribble(
  ~secao,                                  ~descricao,
  "bens_e_direitos",                       "Números das Declarações do Imposto de Renda das Pessoas Físicas - Bens e direitos.",
  "faixa_de_base_de_calculo_anual",        "Resumo das declarações por faixa de base de cálculo anual.",
  "rendimentos_isentos_e_nao_tributaveis", "Agregado dos rendimentos isentos e não tributáveis por faixa de rendimento em salários mínimos.",
  "residencia_capital",                    "Resumo das declarações dos contribuintes residentes nas capitais dos Estados da federação.",
  "dividas_e_onus",                        "Total de valores declarados por tipo de dívida ou ônus.",
  "residencia_uf",                         "Resumo das declarações dos contribuintes residentes nos Estados da federação.",
  "base_calculo_sm_genero",                "Resumo das declarações por faixa de base de cálculo anual (em salários mínimos) e gênero.",
  "doacoes_herancas",                      "Resumo das declarações por faixa de doações e heranças.",
  "rendimento_tributavel_bruto",           "Resumo das declarações por faixa de rendimento tributável bruto.",
  "rendimentos_totais",                    "Resumo das declarações por faixa de rendimentos totais.",
  "rendimentos_trib_exclusiva",            "Resumo das declarações por faixa de rendimentos totais e rendimentos sujeitos à tributação exclusiva.",
  "faixa_etaria_genero",                   "Resumo das declarações por faixa etária e gênero.",
  "natureza_de_ocupacao",                  "Resumo das declarações por natureza da ocupação do contribuinte.",
  "ocupacao_principal",                    "Resumo das declarações pela ocupação principal do contribuinte.",
  "pagamentos_e_doacoes",                  "Total de valores declarados por tipo de pagamento ou doação.",
  "lucros_dividendos_rendimento",          "Resumo das declarações de recebedores de lucros e dividendos + rendimentos de sócio e titular de microempresa por faixa de rendimento total em salários-mínimos.",
  "tributacao_exclusiva",                  "Total de valores sujeitos a tributação exclusiva ou definitiva declarados pelo contribuinte por faixa de rendimento em salários mínimos.",
  "rendimentos_trib_sm",                   "Resumo das declarações por faixa de rendimentos tributáveis em salários-mínimos.",
  "lucros_dividendos_ocupacao",            "Resumo das declarações de recebedores de lucros e dividendos + rendimentos de sócio e titular de microempresa por ocupação principal.",
  "tipo_de_formulario",                    "Resumo das declarações por tipo de formulário.",
  "situacao_fiscal",                       "Resumo das declarações por situação fiscal.",
  "residencia_municipio",                  "Resumo das declarações dos contribuintes residentes nos municípios da federação.",
  "genero_declaracao",                     "Resumo das declarações por gênero e tipo de declaração."
)

irpf_urls_dictionary <- list(
  "bens_e_direitos"            = "https://www.gov.br/receitafederal/dados/bens-e-direitos.csv/@@download/file/Bens%20e%20Direitos.csv",
  "faixa_de_base_de_calculo_anual" = "https://www.gov.br/receitafederal/dados/faixa-de-base-de-calculo-anual.csv",
  "rendimentos_isentos_e_nao_tributaveis" = "https://www.gov.br/receitafederal/dados/rendimentos-isentos-e-nao-tributaveis.csv",
  "residencia_capital"         = "https://www.gov.br/receitafederal/dados/capital-de-estado-de-residencia-do-declarante.csv",
  "dividas_e_onus"             = "https://www.gov.br/receitafederal/dados/dividas-e-onus.csv",
  "residencia_uf"              = "https://www.gov.br/receitafederal/dados/estado-de-residencia-do-declarante.csv",
  "base_calculo_sm_genero"     = "https://www.gov.br/receitafederal/dados/faixa-de-base-de-calculo-em-salarios-minimos-e-genero.csv",
  "doacoes_herancas"           = "https://www.gov.br/receitafederal/dados/faixa-de-doacoes-e-herancas.csv",
  "rendimento_tributavel_bruto"= "https://www.gov.br/receitafederal/dados/faixa-de-rendimento-tributavel-bruto-em-salarios-minimos.csv",
  "rendimentos_totais"         = "https://www.gov.br/receitafederal/dados/faixa-de-rendimentos-totais.csv",
  "rendimentos_trib_exclusiva" = "https://www.gov.br/receitafederal/dados/faixa-de-rendimentos-tributaveis-tributacao-exclusiva-em-salarios-minimos.csv",
  "faixa_etaria_genero"        = "https://www.gov.br/receitafederal/dados/faixa-etaria-do-declarante-e-genero.csv/@@download/file/Faixa%20Et%C3%A1ria%20do%20Declarante%20e%20G%C3%AAnero.csv",
  "natureza_de_ocupacao"       = "https://www.gov.br/receitafederal/dados/natureza-de-ocupacao.csv/@@download/file/Natureza%20de%20Ocupa%C3%A7%C3%A3o.csv",
  "ocupacao_principal"         = "https://www.gov.br/receitafederal/dados/ocupacao-principal-do-declarante.csv/@@download/file/Ocupa%C3%A7%C3%A3o%20Principal%20do%20Declarante.csv",
  "pagamentos_e_doacoes"       = "https://www.gov.br/receitafederal/dados/pagamentos-e-doacoes.csv/@@download/file/Pagamentos%20e%20Doa%C3%A7%C3%B5es.csv",
  "lucros_dividendos_rendimento" = "https://www.gov.br/receitafederal/dados/recebedores-de-lucros-e-dividendos-rend-socio-e-titular-microempresa-por-faixa-de-rendimento-total.csv/@@download/file/Recebedores%20de%20Lucros%20e%20Dividendos%20+%20Rend.S%C3%B3cio%20e%20Titular%20Microempresa%20por%20Faixa%20de%20Rendimento%20Total%20(em%20sal%C3%A1rios-m%C3%ADnimos).csv",
  "tributacao_exclusiva"       = "https://www.gov.br/receitafederal/dados/rendimentos-sujeitos-a-tributacao-exclusiva_definitiva.csv/@@download/file/Rendimentos%20Sujeitos%20%C3%A0%20Tributa%C3%A7%C3%A3o%20Exclusiva_Definitiva.csv",
  "rendimentos_trib_sm"        = "https://www.gov.br/receitafederal/dados/rendimentos-tributaveis-por-faixa-de-salarios-minimos.csv/@@download/file/Rendimentos%20Tribut%C3%A1veis%20por%20Faixa%20de%20Sal%C3%A1rios-M%C3%ADnimos.csv",
  "lucros_dividendos_ocupacao" = "https://www.gov.br/receitafederal/dados/recebedores-de-lucros-e-dividendos-rend-socio-e-titular-microempresa-por-ocupacao-principal.csv/@@download/file/Recebedores%20de%20Lucros%20e%20Dividendos%20+%20Rend.S%C3%B3cio%20e%20Titular%20Microempresa%20por%20Ocupa%C3%A7%C3%A3o%20Principal.csv",
  "tipo_de_formulario"         = "https://www.gov.br/receitafederal/dados/tipo-de-formulario.csv/@@download/file/Tipo%20de%20Formul%C3%A1rio.csv",
  "situacao_fiscal"            = "https://www.gov.br/receitafederal/dados/situacao-fiscal.csv/@@download/file/Situa%C3%A7%C3%A3o%20Fiscal.csv",
  "residencia_municipio"       = "https://www.gov.br/receitafederal/dados/municipio-de-residencia-do-declarante-e-tipo-de-formulario.csv/@@download/file/Munic%C3%ADpio%20de%20Resid%C3%AAncia%20do%20Declarante%20e%20Tipo%20de%20Formul%C3%A1rio.csv",
  "genero_declaracao"          = "https://www.gov.br/receitafederal/dados/genero-e-tipo-de-declaracao.csv/@@download/file/G%C3%AAnero%20e%20Tipo%20de%20Declara%C3%A7%C3%A3o.csv"
)

irpf_metadata_storage <- list()

irpf_metadata_storage[["bens_e_direitos"]] <- tibble::tribble(
  ~atributo, ~descricao,
  "ano_calendario", "Informa o ano calendário da declaração.",
  "acoes_inclusive_as_provenientes_de_linha_telefonica", "Ações declaradas como bem ou direito.",
  "aeronave", "Aeronaves declaradas.",
  "apartamento", "Apartamentos declarados.",
  "aplicacao_de_renda_fixa_cdb_rdb_e_outros", "Aplicações de renda fixa.",
  "bem_relacionado_com_o_exercicio_da_atividade_autonoma", "Bens de atividade autônoma.",
  "benfeitorias", "Benfeitorias declaradas.",
  "caderneta_de_poupanca", "Saldo de cadernetas de poupança.",
  "casa", "Casas declaradas.",
  "consorcio_nao_contemplado", "Consórcios não contemplados.",
  "construcao", "Construções em andamento.",
  "credito_decorrente_de_alienacao", "Créditos de vendas de bens.",
  "credito_decorrente_de_emprestimo", "Créditos de empréstimos concedidos.",
  "criptoativo_bitcoin_btc", "Criptoativos Bitcoin.",
  "demais_criptoativos_nao_considerados_criptomoedas_payment_token_security_token_ou_utility_token", "Outros criptoativos (tokens).",
  "dep_bancario_em_conta_corrente_no_ext_exceto_o_informado_sob_cod_80_saldo_derex_lei_11371_2006", "Depósitos no exterior.",
  "deposito_bancario_em_conta_corrente_no_pais", "Depósitos no Brasil.",
  "demais_bens_e_direitos", "Outros bens e direitos.",
  "dinheiro_em_especie_moeda_nacional", "Dinheiro em espécie (R$).",
  "dinheiro_em_especie_moeda_estrangeira", "Dinheiro em espécie (Moeda Estrangeira).",
  "direito_de_autor_de_inventor_e_patente", "Direitos autorais e patentes.",
  "direito_de_lavra_e_assemelhado", "Direitos de mineração.",
  "embarcacao", "Embarcações declaradas.",
  "fundo_de_curto_prazo", "Fundos de curto prazo.",
  "fundo_de_investimento_imobiliario", "Fundos Imobiliários (FII).",
  "fundo_de_longo_prazo_e_fundo_de_investimentos_em_direitos_creditorios_fidc", "Fundos de longo prazo e FIDC.",
  "fundos_acoes_mutuos_privat_invest_emp_emerg_invest_participacao_e_invest_ind_mercado", "Diversos fundos de investimento.",
  "galpao", "Galpões declarados.",
  "imovel_rural", "Imóveis rurais.",
  "invalido", "Valores inválidos declarados.",
  "joia_quadro_objeto_de_arte_de_colecao_antiguidade_etc", "Objetos de arte e coleção.",
  "leasing", "Valores de leasing.",
  "licenca_e_concessao_especiais", "Licenças especiais.",
  "linha_telefonica", "Linhas telefônicas.",
  "loja", "Lojas declaradas.",
  "mercados_futuros_de_opcoes_e_a_termo", "Mercado de derivativos.",
  "nao_informado", "Atributos não informados.",
  "ouro_ativo_financeiro", "Ouro como ativo financeiro.",
  "outras_aplicacoes_e_investimentos", "Outras aplicações financeiras.",
  "outras_participacoes_societarias", "Outras participações em empresas.",
  "outros_bens_e_direitos", "Outros ativos.",
  "outros_bens_imoveis", "Outros imóveis.",
  "outros_bens_moveis", "Outros móveis.",
  "outros_creditos_e_poupanca_vinculados", "Créditos vinculados.",
  "outros_criptoativos_do_tipo_moeda_digital_conhecidos_como_altcoins_eth_xrp_bch_usdt_link_ltc", "Altcoins diversas.",
  "outros_depositos_a_vista_e_numerario", "Outros depósitos.",
  "outros_fundos", "Fundos não especificados.",
  "plano_pait_e_caderneta_peculio", "Plano PAIT e pecúlio.",
  "poupanca_for_construction_or_acquisition_of_real_estate", "Poupança para imóveis.",
  "predio_comercial", "Prédios comerciais.",
  "predio_residencial", "Prédios residenciais.",
  "quotas_ou_quinhoes_de_capital", "Quotas de capital social.",
  "sala_ou_conjunto", "Salas comerciais.",
  "saldo_derex_lei_11371_2006", "Saldo DEREX.",
  "terreno", "Terrenos declarados.",
  "titulo_de_clube_e_assemelhado", "Títulos de clubes.",
  "veiculo_automotor_terrestre_caminhao_automovel_moto_etc", "Veículos terrestres.",
  "vgbl_vida_gerador_de_beneficio_livre", "Investimentos VGBL.",
  "terra_nua", "Terra nua de imóvel rural.",
  "fundo_de_investimento_financeiro_fif", "Fundos FIF.",
  "outras_informacoes_de_outros_bens_e_direitos", "Informações complementares."
)

irpf_metadata_storage[["rendimentos_isentos_e_nao_tributaveis"]] <- tibble::tribble(
  ~atributo, ~descricao,
  "ano_calendario", "Ano calendário da declaração.",
  "faixa_de_salarios_minimos", "Faixas de rendimentos em salários-mínimos.",
  "bolsas_de_estudo_e_de_pesquisa_caracterizadas_como_doacao_exceto_medico_residente_ou_pronatec_...", "Bolsas de estudo comuns.",
  "bolsas_de_estudo_e_de_pesquisa_caracterizadas_como_doacao_quando_recebidas_por_medico_residente_...", "Bolsas de residência/Pronatec.",
  "capital_das_apolices_de_seguro_ou_peculio_pago_por_morte_...", "Seguros e pecúlios por morte/invalidez.",
  "indenizacoes_por_rescisao_de_contrato_de_trabalho_inclusive_fgts", "Rescisão trabalhista e FGTS.",
  "ganho_de_capital_na_alienacao_de_bem_ate_20_000_ou_35_000", "Ganhos de capital isentos (limites mensais).",
  "ganho_de_capital_na_alienacao_do_unico_imovel_ate_440_000", "Venda de único imóvel.",
  "ganho_de_capital_na_venda_de_imoveis_residenciais_para_aquisicao_de_outro", "Venda para compra de outro imóvel (180 dias).",
  "ganho_de_capital_na_alienacao_de_moeda_estrangeira_ate_5_000_usd", "Venda de moeda estrangeira.",
  "lucros_e_dividendos_recebidos", "Lucros e dividendos recebidos (Isentos).",
  "parcela_isenta_de_proventos_de_aposentadoria_65_anos_ou_mais", "Aposentadoria isenta para idosos.",
  "pensao_proventos_de_aposentadoria_por_molestia_grave_ou_acidente", "Aposentadoria por invalidez/doença grave.",
  "rendimentos_de_cadernetas_de_poupanca_lca_lci_cra_cri", "Rendimentos de poupança e letras de crédito.",
  "rendimento_de_socio_ou_titular_de_me_epp_simples_nacional", "Rendimento de sócio de microempresa.",
  "transferencias_patrimoniais_doacoes_e_herancas", "Doações e heranças recebidas.",
  "imposto_de_renda_compensado_judicialmente", "IR compensado judicialmente.",
  "x75_dos_rendimentos_do_trabalho_no_exterior_convertidos_em_reais", "Trabalho assalariado no exterior (servidores).",
  "incorporacao_de_reservas_ao_capital_bonificacoes_em_acoes", "Bonificações em ações.",
  "transferencias_patrimoniais_meacao_e_dissolucao_conjugal", "Meação e dissolução conjugal.",
  "ganhos_liquidos_em_bolsa_ate_20_000_mensais", "Ganhos em bolsa (isento até R$ 20k).",
  "ganhos_liquidos_com_ouro_ativo_financeiro", "Ganhos com ouro (isento até R$ 20k).",
  "rendimento_bruto_transporte_carga_trator_maquina_agricola", "Transporte de carga (parcela isenta).",
  "rendimento_bruto_transporte_passageiros", "Transporte de passageiros (parcela isenta).",
  "restituicao_de_irpf_de_anos_anteriores", "Restituição de anos anteriores.",
  "parcela_isenta_atividade_rural", "Atividade rural (parcela isenta).",
  "recuperacao_de_prejuizos_em_renda_variavel", "Recuperação de perdas em bolsa/FII.",
  "demais_rend_isentos_dos_dependentes", "Rendimentos isentos de dependentes.",
  "beneficios_voluntario_fifa_loc", "Benefícios Copa do Mundo (FIFA/LOC).",
  "outros", "Outros rendimentos isentos."
)

irpf_metadata_storage[["dividas_e_onus"]] <- tibble::tribble(
  ~atributo, ~descricao,
  "ano_calendario", "Informa o ano calendário da declaração.",
  "emprestimos_contraidos_no_exterior", "Empréstimos no exterior.",
  "estabelecimento_bancario_comercial", "Dívidas com bancos comerciais.",
  "outras_dividas_e_onus_reais", "Outras dívidas reais.",
  "outras_pessoas_juridicas", "Dívidas com outras PJs.",
  "pessoas_fisicas", "Dívidas com pessoas físicas.",
  "soc_de_credito_financiamento_e_investimento", "Dívidas com financeiras.",
  "outros", "Outras dívidas declaradas.",
  "invalido", "Dívidas inválidas."
)

header_mappings <- list(
  "faixa_de_base_de_calculo_anual" = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "tipo_de_declaracao", "Individual ou Conjunta.", "faixa_de_rendimento", "Faixa de rendimento agrupada.", "quantidade_de_declarantes", "Quantidade de declarantes na faixa."),
  "residencia_capital"            = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "capital_estado", "Capital de residência.", "quantidade_de_declarantes", "Quantidade de declarantes na capital."),
  "residencia_uf"                 = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "estado", "UF de residência.", "quantidade_de_declarantes", "Quantidade de declarantes no estado."),
  "base_calculo_sm_genero"        = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "genero", "Gênero do declarante.", "faixa_de_sm_mensal", "Faixa em salários-mínimos.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "doacoes_herancas"              = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "faixa_de_sm_mensal", "Faixa de doações/heranças recebidas.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "rendimento_tributavel_bruto"   = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "faixa_de_sm_mensal", "Faixa de rendimento bruto.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "rendimentos_totais"            = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "faixa_de_sm_mensal", "Faixa de rendimento total.", "quantidade_de_declarantes", "Quantidade de declarantes na faixa."),
  "rendimentos_trib_exclusiva"    = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "faixa_de_sm_mensal", "Faixa de tributável + exclusiva.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "faixa_etaria_genero"           = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "tipo_de_declaracao", "Tipo de declaração.", "faixa_etaria", "Faixa de idade.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "natureza_de_ocupacao"          = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "natureza_da_ocupacao", "Natureza da ocupação.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "ocupacao_principal"            = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "ocupacao", "Ocupação principal.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "lucros_dividendos_rendimento"  = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "faixa_de_sm_mensal", "Faixa de rendimento total em SM.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "situacao_fiscal"               = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "situacao_fiscal", "Imposto a pagar ou a restituir.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "tipo_de_formulario"            = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "tipo_de_formulario", "Tipo de formulário utilizado.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "residencia_municipio"          = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "tipo_de_formulario_de_declaracao", "Completo ou Simplificado.", "municipio", "Município de residência.", "quantidade_de_declarantes", "Quantidade de declarantes."),
  "genero_declaracao"             = tibble::tribble(~atributo, ~descricao, "ano_calendario", "Ano calendário.", "genero", "Gênero do contribuinte.", "tipo_de_declaracao", "Individual ou Conjunta.", "quantidade_de_declarantes", "Quantidade de declarantes.")
)

for (sec in names(header_mappings)) {
  irpf_metadata_storage[[sec]] <- dplyr::bind_rows(header_mappings[[sec]], standard_tax_cols)
}

irpf_sections_catalog <- tibble::as_tibble(irpf_sections_catalog)
irpf_metadata_storage <- lapply(irpf_metadata_storage, tibble::as_tibble)

usethis::use_data(
  irpf_sections_catalog,
  irpf_urls_dictionary,
  irpf_metadata_storage,
  internal = TRUE,
  overwrite = TRUE
)
